version: '3.8'

services:
  rust-db:
    image: gourangadassamrat/polyhymnia:rust-db-v<VERSION>
    ports:
      - '50051:50051'
    restart: unless-stopped

  cpp-engine:
    image: gourangadassamrat/polyhymnia:cpp-engine-v<VERSION>
    ports:
      - '50052:50052'
    restart: unless-stopped

  go-gateway:
    image: gourangadassamrat/polyhymnia:go-gateway-v<VERSION>
    ports:
      - '8080:8080'
    depends_on:
      - rust-db
      - cpp-engine
    restart: unless-stopped

  frontend:
    image: gourangadassamrat/polyhymnia:frontend-v<VERSION>
    ports:
      - '5500:80'
    restart: unless-stopped
